### ISSUE TITLE
npm package depends on itself

### ISSUE THREAD

**Issue by millette** [jameslittle230/stork#185] opened 2021-05-30 17:41 UTC
Noticed on [npm](https://www.npmjs.com/package/stork-search) that stork-search depends on itself. See this line in `package.json`:

https://github.com/jameslittle230/stork/blob/007d6bd34a918f5ca7df48a011b267f219a78cfd/package.json#L73

See also #129

**Comment by jameslittle230** [comment] 2021-05-30 21:56
Hey! Yeah, the NPM package isn't really meant for human consumption at this point. Going to mark this as a dupe of #129, since presumably when that gets fixed, this won't be an issue anymore.

**Closed by jameslittle230** 2021-05-30 21:56 UTC
