### ISSUE TITLE
Executable name mismatch on master: help text says stork and executable is called `stork-cli`

### ISSUE THREAD

**Issue by deining** [jameslittle230/stork#218] opened 2021-12-19 10:24 UTC
Following the documentation, I tried to build `stork`:

```
cargo install stork-search
```

Compilation fails, however:

```
   Compiling stork-search v1.3.0
error: expected `,`
  --> C:\Users\Andreas\.cargo\registry\src\github.com-1ecc6299db9ec823\stork-search-1.3.0\src\wasm.rs:38:35
   |
38 |     #[wasm_bindgen(js_namespace = console)]
   |                                   ^^^^^^^

error: failed to compile `stork-search v1.3.0`, intermediate artifacts can be found at `C:\Users\xxx\AppData\Local\Temp\cargo-installW9NjuQ`

Caused by:
  could not compile `stork-search` due to previous error
```

My environment:

- Windows 10 pro x64, Version 21H1 (Build: 19044.1415)
- cargo 1.57.0 (b2e52d7ca 2021-10-21)
- npm 8.30
- wasm-pack 0.10.2

I didn't give up, cloned the stork github repo at HEAD and issued `cargo build`. This time with more luck, compilation was successful, so I guess my build environment is o.k.

So now I have `stork` up and running: 😄 

```
C:\Users\Andreas>stork-cli
Stork 1.4.0
James Little <https://jameslittle.me>
Impossibly fast web search, made for static sites - https://stork-search.net

USAGE:
    stork [SUBCOMMAND]
```

A few comments from a user that has first time contact with stork:

- I was surprised to see `Stork 1.4.0`. According to your repo, Stork is at version `1.3.0`, so I expected to see something like `1.4.0-dev`, `1.4-dev@b83157f` or so.
- The executable produced is named `stork-cli`, but usage message tells `stork [SUBCOMMAND]`. Also documentation mentions `stork` all the times. Certainly not a big deal, but it confused me quite a bit. I guess I will rename my file to `stork.exe` now. 😄

**Comment by deining** [comment] 2021-12-19 10:36
Uups, I was bit fast with my comment. Inside my repo, I just checked out reviosion at tag v1.3.0 and built the project again. Now the exectuable is named `stork.exe`, sorry for the noise. Are you planning to change it to `stork-cli.exe`? If so, you could adapt the name in the synopsis.

**Comment by jameslittle230** [comment] 2021-12-19 16:05
👋 Thanks for checking out Stork!

This sounds like two independent issues, if I understand correctly:

* A build issue with `cargo install`, which looks like a duplicate of https://github.com/jameslittle230/stork/issues/188
* The command line help text refers to the executable name as `stork-cli` instead of `stork`

I'm tracking the build issue in #188 above, and I think a few other folks have come up with some workarounds, though I'm glad you got Stork running.

The executable should be named `stork` both in 1.3.0 and the upcoming 1.4.0. I think I saw that mismatch between executable name and the helptext recently and fixed it in a new branch I'm working on, but I'll make sure it gets in the next release, and use this issue to track that.

> I expected to see something like 1.4.0-dev, 1.4-dev@b83157f or so.

I don't think there'd be an easy way of changing the versions around like that, at least not without setting up an automated nightly release (which I don't plan on doing for time/prioritization reasons). The project version is set as `1.4.0` on the master branch so that the next release, which will get tagged off master, has the right version number automatically.

**Comment by deining** [comment] 2021-12-19 19:54
> which looks like a duplicate of [cargo install stork-search failing on wasm_bindgen syntax #188](https://github.com/jameslittle230/stork/issues/188)

Yes, this is a duplicate. I didn't see the existing ticket, sorry.

> I'm tracking the build issue in #188 above, and I think a few other folks have come up with some workarounds

Adding the `--locked` worked for me and solved my problem. As this problem isn't solved yet, I think we should mention this in the `installation` section of the documentation.

**Closed** 2022-01-03 01:58 UTC
Labels: type:bug, type:support
