### ISSUE TITLE
Option to find files automatically instead of having to specify them in config file

### ISSUE THREAD

**Issue by kkwteh** [jameslittle230/stork#308] opened 2022-07-29 15:25 UTC
It would nice to be able to point the stork command line program to a directory and have it create the index automatically without having to create the config file that lists all of the file objects.

In each of my html files, I already have title and url data inside meta tags and the title tag, and Stork should be able to just parse these out of the document automatically.

**Comment by jameslittle230** [comment] 2022-07-29 23:02
Hi @kkwteh, thanks for submitting this feature request! I'm going to close it as a duplicate of https://github.com/jameslittle230/stork/issues/9, but I'll remember that you wanted it and prioritize accordingly!

**Closed by jameslittle230** 2022-07-29 23:02 UTC
