### ISSUE TITLE
Demo website is not working

### ISSUE THREAD

**Issue by jakearlen879** [jameslittle230/stork#126] opened 2021-01-08 18:24 UTC
Hi,

The demo website (https://stork-search.net) is not working. I have the following errors in the Chrome console:

![image](https://user-images.githubusercontent.com/74742569/104050308-ba9b4d00-51e6-11eb-890a-a2138557214b.png)

I also tried on Firefox and in Incognito mode.

**Comment by jameslittle230** [comment] 2021-01-09 01:20
Hi @jakearlen879 - can you describe what sort of browser setup you're using? I see the site making requests to `codota.com` and to Google Analytics, and I see code being run from Jquery and `livecode-util.js`, none of which are part of the Stork Site code (you can audit yourself by seeing the source code of the site at this repo: https://github.com/stork-search/site)

Given that the site seems to be working for nearly everyone else, and given that I don't see any of those console errors on any of my browsers, I think this might be something on your end.

**Comment by em-** [comment] 2021-01-10 17:27
It's not working for me either with Firefox 84.0.1/Linux, but I get no specific error on the console so I assume it is a different issue (let me know if you prefer I open a separate ticket)

In my case, typing in the search box does not make the dropdown show up at all. In the console there's a 404 on https://stork-search.net/icons/icon-512x512.png but I'd be surprised if it was related. An `entityManager` object with `{indexVersion: stork-3, name: federalist, ...}` is also printed on the console.

With Chromium 87.0.4280.88/Linux and Chrome 87.0.4280.141/Linux I found an interesting behavior: on the first ever load of the demo nothing happens, like in the Firefox case. But once reloading the page, things magically start to work. I can easily reproduce it by nuking the Chrome cache data folder and restarting it.

**Comment by reese** [comment] 2021-01-10 17:38
I think that 404 is unrelated, and that `entityManager` also prints for me on a successful load -- I'd assume that's just a stray `console.log`. Do either of you have some kind of extensions installed?

I'd also be curious about what OS @jakearlen879 is using in case that could have something to do with it. I tried to reproduce on Firefox 84 and Chrome 87 but it worked for me even when clearing the cache. Seeing no error in the console does seem fishy to me though, that almost just sounds like an unexpected case in the JS or something.

**Comment by jakearlen879** [comment] 2021-01-12 22:57
It's working now. I'm using Windows 10. Thank you for your help.

**Comment by jameslittle230** [comment] 2021-01-12 23:46
Glad to hear it - thanks for getting back.

@em- This might be an unrelated bug on the demo site. Could you visit my personal site (https://jameslittle.me) and see if Stork works on that page?

I'm going to close this issue -- feel free to re-open it if there are continued Stork issues. If the bug is only present on the demo site, feel free to open a new issue on the site's repo: https://github.com/stork-search/site

Thanks for writing in!
James

**Closed by jameslittle230** 2021-01-12 23:46 UTC
Labels: bug, cant-reproduce
